version: '3.9'

services:
  app:
    build: .
    container_name: portafolio_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./database.db:/app/database.db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload