"""tabla porcentajes

Revision ID: 4f27abf9f4dc
Revises: ae6a5da5ee5d
Create Date: 2025-06-27 21:40:18.747201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f27abf9f4dc'
down_revision: Union[str, None] = 'ae6a5da5ee5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RepositorioLenguajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Lenguaje', sa.String(length=150), nullable=True),
    sa.Column('Valor', sa.DECIMAL(precision=2), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_RepositorioLenguajes_Lenguaje'), 'RepositorioLenguajes', ['Lenguaje'], unique=False)
    op.create_index(op.f('ix_RepositorioLenguajes_id'), 'RepositorioLenguajes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_RepositorioLenguajes_id'), table_name='RepositorioLenguajes')
    op.drop_index(op.f('ix_RepositorioLenguajes_Lenguaje'), table_name='RepositorioLenguajes')
    op.drop_table('RepositorioLenguajes')
    # ### end Alembic commands ###
