"""nueva estructura

Revision ID: 572d3a908e20
Revises: 
Create Date: 2025-06-04 22:47:19.454405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572d3a908e20'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Sistema', sa.String(length=150), nullable=True),
    sa.Column('Descripcion', sa.String(length=200), nullable=False),
    sa.Column('Logo', sa.String(length=100), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Proyectos_Sistema'), 'Proyectos', ['Sistema'], unique=False)
    op.create_index(op.f('ix_Proyectos_id'), 'Proyectos', ['id'], unique=False)
    op.create_table('DetalleBackend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Repositorio', sa.String(length=200), nullable=True),
    sa.Column('Framework', sa.String(length=100), nullable=True),
    sa.Column('Lenguaje', sa.String(length=100), nullable=True),
    sa.Column('BaseDatos', sa.String(length=100), nullable=True),
    sa.Column('Alojamiento', sa.String(length=100), nullable=True),
    sa.Column('SO', sa.String(length=100), nullable=True),
    sa.Column('Urls', sa.Text(), nullable=True),
    sa.Column('ServidorWeb', sa.String(length=100), nullable=True),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['Proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DetalleBackend_id'), 'DetalleBackend', ['id'], unique=False)
    op.create_table('DetalleFrontend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Repositorio', sa.String(length=200), nullable=True),
    sa.Column('Framework', sa.String(length=100), nullable=True),
    sa.Column('Lenguaje', sa.String(length=100), nullable=True),
    sa.Column('Alojamiento', sa.String(length=100), nullable=True),
    sa.Column('SO', sa.String(length=100), nullable=True),
    sa.Column('Urls', sa.Text(), nullable=True),
    sa.Column('ServidorWeb', sa.String(length=100), nullable=True),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['Proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DetalleFrontend_id'), 'DetalleFrontend', ['id'], unique=False)
    op.create_table('DetalleMovil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Repositorio', sa.String(length=200), nullable=True),
    sa.Column('Framework', sa.String(length=100), nullable=True),
    sa.Column('Lenguaje', sa.String(length=100), nullable=True),
    sa.Column('VersionAndroid', sa.String(length=100), nullable=True),
    sa.Column('VersioniOS', sa.String(length=100), nullable=True),
    sa.Column('EnlaceDescarga', sa.Text(), nullable=True),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['Proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DetalleMovil_id'), 'DetalleMovil', ['id'], unique=False)
    op.create_table('ProyectosTags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Tag', sa.String(length=200), nullable=True),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['Proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ProyectosTags_id'), 'ProyectosTags', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ProyectosTags_id'), table_name='ProyectosTags')
    op.drop_table('ProyectosTags')
    op.drop_index(op.f('ix_DetalleMovil_id'), table_name='DetalleMovil')
    op.drop_table('DetalleMovil')
    op.drop_index(op.f('ix_DetalleFrontend_id'), table_name='DetalleFrontend')
    op.drop_table('DetalleFrontend')
    op.drop_index(op.f('ix_DetalleBackend_id'), table_name='DetalleBackend')
    op.drop_table('DetalleBackend')
    op.drop_index(op.f('ix_Proyectos_id'), table_name='Proyectos')
    op.drop_index(op.f('ix_Proyectos_Sistema'), table_name='Proyectos')
    op.drop_table('Proyectos')
    # ### end Alembic commands ###
