"""tabla sesion

Revision ID: 8d28deb735d1
Revises: 572d3a908e20
Create Date: 2025-06-18 22:54:42.565093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d28deb735d1'
down_revision: Union[str, None] = '572d3a908e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SesionActiva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('DataSesion', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_SesionActiva_DataSesion'), 'SesionActiva', ['DataSesion'], unique=False)
    op.create_index(op.f('ix_SesionActiva_id'), 'SesionActiva', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SesionActiva_id'), table_name='SesionActiva')
    op.drop_index(op.f('ix_SesionActiva_DataSesion'), table_name='SesionActiva')
    op.drop_table('SesionActiva')
    # ### end Alembic commands ###
