"""tabla frameworks

Revision ID: ae6a5da5ee5d
Revises: 8d28deb735d1
Create Date: 2025-06-26 22:13:11.664943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6a5da5ee5d'
down_revision: Union[str, None] = '8d28deb735d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RepositoriosFrameworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Framework', sa.String(length=150), nullable=True),
    sa.Column('NombreRepositorio', sa.String(length=200), nullable=False),
    sa.Column('Url', sa.String(length=200), nullable=True),
    sa.Column('Tipo', sa.String(length=200), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_RepositoriosFrameworks_Framework'), 'RepositoriosFrameworks', ['Framework'], unique=False)
    op.create_index(op.f('ix_RepositoriosFrameworks_id'), 'RepositoriosFrameworks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_RepositoriosFrameworks_id'), table_name='RepositoriosFrameworks')
    op.drop_index(op.f('ix_RepositoriosFrameworks_Framework'), table_name='RepositoriosFrameworks')
    op.drop_table('RepositoriosFrameworks')
    # ### end Alembic commands ###
